twig:
    file_name_pattern: '*.twig'
    globals:
        app_version: '%app.version%'
        app_latest_version: '%app.latest_version%'
        dev_tools: '@App\Dev\DevTools'

when@test:
    twig:
        strict_variables: true
